-- Enable pgcrypto for UUID generation if not already enabled
create extension if not exists pgcrypto;

-- 1. UNITS
create table if not exists public.units (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  address text,
  active boolean default true,
  created_at timestamptz default now()
);

alter table public.units enable row level security;
create policy "Enable all for authenticated users" on public.units for all using (auth.role() = 'authenticated');

-- 2. PROFILES (Modified from original to include inferred fields)
create table if not exists public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  full_name text,
  avatar_url text,
  role text default 'user',
  permissions jsonb default '[]'::jsonb,
  unit_id uuid references public.units(id),
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on public.profiles for update
  using ( auth.uid() = id );

create policy "Admins and Managers can update any profile"
  on public.profiles for update
  using (
    auth.uid() in (
      select id from public.profiles where role in ('admin', 'manager')
    )
  );

-- 3. PRODUCTS
create table if not exists public.products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  unit text,
  quantity integer default 0,
  image_url text,
  created_at timestamptz default now()
);

alter table public.products enable row level security;
create policy "Enable all for authenticated users" on public.products for all using (auth.role() = 'authenticated');

-- 4. REQUISITIONS
create table if not exists public.requisitions (
  id uuid default gen_random_uuid() primary key,
  display_id bigint generated by default as identity,
  requester_id uuid references auth.users(id),
  unit_id uuid references public.units(id),
  status text default 'PENDENTE',
  created_at timestamptz default now()
);

alter table public.requisitions enable row level security;
create policy "Enable all for authenticated users" on public.requisitions for all using (auth.role() = 'authenticated');

-- 5. REQUISITION ITEMS
create table if not exists public.requisition_items (
  id uuid default gen_random_uuid() primary key,
  requisition_id uuid references public.requisitions(id) on delete cascade,
  product_id uuid references public.products(id),
  quantity integer,
  authorized_quantity integer
);

alter table public.requisition_items enable row level security;
create policy "Enable all for authenticated users" on public.requisition_items for all using (auth.role() = 'authenticated');

-- 6. INVENTORY MOVEMENTS
create table if not exists public.inventory_movements (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references public.products(id),
  type text check (type in ('IN', 'OUT')),
  quantity integer,
  user_id uuid references public.profiles(id),
  unit_id uuid references public.units(id),
  reason text,
  movement_date timestamptz default now(),
  created_at timestamptz default now()
);

alter table public.inventory_movements enable row level security;
create policy "Enable all for authenticated users" on public.inventory_movements for all using (auth.role() = 'authenticated');

-- 7. SUPPLIERS
create table if not exists public.suppliers (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  cnpj text,
  address_street text,
  address_number text,
  address_complement text,
  address_neighborhood text,
  address_city text,
  address_state text,
  phone text,
  whatsapp text,
  seller_name text,
  seller_phone text,
  seller_whatsapp text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.suppliers enable row level security;
create policy "Enable all for authenticated users" on public.suppliers for all using (auth.role() = 'authenticated');

-- 8. LOGS
create table if not exists public.logs (
  id uuid default gen_random_uuid() primary key,
  action text,
  entity text,
  entity_id text,
  details jsonb,
  user_id uuid references auth.users(id),
  created_at timestamptz default now()
);

alter table public.logs enable row level security;
create policy "Enable all for authenticated users" on public.logs for all using (auth.role() = 'authenticated');


-- TRIGGERS AND FUNCTIONS

-- Handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Delete auth user on profile delete (from supabase_security.sql)
create or replace function public.delete_auth_user()
returns trigger
language plpgsql
security definer
as $$
begin
  delete from auth.users where id = old.id;
  return old;
end;
$$;

drop trigger if exists on_profile_delete on public.profiles;
create trigger on_profile_delete
  after delete on public.profiles
  for each row execute procedure public.delete_auth_user();
